//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeStoreManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_LichLamPartTime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CT_LichLamPartTime()
        {
            this.CT_CaLamPartTime = new HashSet<CT_CaLamPartTime>();
        }
    
        public int ma_ct_lich_partTime { get; set; }
        public Nullable<int> ma_lich_partTime { get; set; }
        public Nullable<int> ma_nhan_vien { get; set; }
        public Nullable<int> so_gio_lam { get; set; }
        public Nullable<decimal> tien_luong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_CaLamPartTime> CT_CaLamPartTime { get; set; }
        public virtual LichLamPartTime LichLamPartTime { get; set; }
    }
}
