//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeStoreManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PhieuNhapHang
    {
        public int ma_ct_phieu_nhap_hang { get; set; }
        public Nullable<int> ma_phieu_nhap_hang { get; set; }
        public string ten_mat_hang { get; set; }
        public Nullable<decimal> gia_tien { get; set; }
        public Nullable<int> so_luong { get; set; }
        public Nullable<decimal> tong_tien { get; set; }
    
        public virtual PhieuNhapHang PhieuNhapHang { get; set; }
    }
}
