//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeStoreManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int ma_hoa_don { get; set; }
        public Nullable<System.DateTime> ngay_xuat_hoa_don { get; set; }
        public Nullable<decimal> tong_tien { get; set; }
        public Nullable<int> ma_ban_an { get; set; }
    }
}
