//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeStoreManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichLamPartTime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LichLamPartTime()
        {
            this.CT_LichLamPartTime = new HashSet<CT_LichLamPartTime>();
        }
    
        public int ma_lich_partTime { get; set; }
        public Nullable<System.DateTime> ngay_bat_dau { get; set; }
        public Nullable<System.DateTime> ngay_ket_thuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_LichLamPartTime> CT_LichLamPartTime { get; set; }
    }
}
