//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeStoreManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiNhanVien
    {
        public int ma_loai_nhan_vien { get; set; }
        public string ten_loai_nhan_vien { get; set; }
        public Nullable<decimal> tien_luong { get; set; }
    }
}
