//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeStoreManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luong
    {
        public int ma_tinh_luong { get; set; }
        public Nullable<System.DateTime> ngay_tinh_luong { get; set; }
        public Nullable<decimal> tong_tien_luong { get; set; }
    }
}
