//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeStoreManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonAn()
        {
            this.CT_HoaDon = new HashSet<CT_HoaDon>();
        }
    
        public int ma_mon_an { get; set; }
        public string ten_mon_an { get; set; }
        public Nullable<decimal> gia_tien { get; set; }
<<<<<<< HEAD
        public Nullable<int> ma_loai_mon_an { get; set; }
=======
        public int ma_loai_mon_an { get; set; }
>>>>>>> 025f1cb9bd249f32bf8a2ebbb20dc8c50c363272
        public string nguyen_lieu { get; set; }
        public string mo_ta { get; set; }
        public byte[] anh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HoaDon> CT_HoaDon { get; set; }
        public virtual LoaiMonAn LoaiMonAn { get; set; }
    }
}
