//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeStoreManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyDinh
    {
        public int ma_quy_dinh { get; set; }
        public Nullable<int> so_ban { get; set; }
        public Nullable<int> tuoi_toi_thieu_nv { get; set; }
        public Nullable<int> tuoi_toi_da_nv { get; set; }
        public Nullable<System.DateTime> ngay_tinh_luong { get; set; }
        public Nullable<int> san_pham_uu_dai { get; set; }
        public Nullable<int> count_uu_dai { get; set; }
        public Nullable<decimal> muc_tien_nhan_uu_dai { get; set; }
    
        public virtual MonAn MonAn { get; set; }
    }
}
