//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeStoreManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoanAdmin
    {
        public int ma_tai_khoan { get; set; }
        public string ten_dang_nhap { get; set; }
        public string mat_khau { get; set; }
        public string ho_ten { get; set; }
        public string dia_chi { get; set; }
        public string gmail { get; set; }
        public string so_dien_thoai { get; set; }
        public string image_source { get; set; }
    }
}
